name: 'Docker Hub Description'
author: 'Peter Evans'
description: 'An action to update a Docker Hub repository description from README.md'
inputs:
  username:
    description: Docker Hub username
    required: true
  password:
    description: Docker Hub password or Personal Access Token with read/write/delete scope
    required: true
  repository:
    description: >
      Docker Hub repository in the format `<namespace>/<name>`
      Default: `github.repository`
  short-description:
    description: Docker Hub repository short description
  readme-filepath:
    description: >
      Path to the repository readme
      Default: `./README.md`
  enable-url-completion:
    description: >
      Enables completion of relative URLs to absolute ones
      Default: `false`
  image-extensions:
    description: >
      File extensions that will be treated as images
      Default: `bmp,gif,jpg,jpeg,png,svg,webp`
runs:
  using: 'node24'
  main: 'dist/index.js'
branding:
  icon: 'upload'
  color: 'blue'
